### PR TITLE
Allow subclassing of ServiceException

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
simpler code + encapsulation of http-remoting API in fewer places.
```
throw new ServiceException(FOO_NOT_FOUND, SafeArg.of("foo", foo));
```
vs
```
throw new FooNotFoundException(foo);
```

**Comment by uschi2000** [comment]
Thoughts?

**Comment by markelliot** [comment]
In general I think we wan to encourage use of an Exception factory rather than simply extending + throwing exceptions. Not sure this makes a big difference if we're going to generate that factory?

**Comment by markelliot** [comment]
also something to be said for knowing if the exception being thrown is in fact a ServiceException or just some other random exception

**Comment by uschi2000** [comment]
I don't quite follow your two comments, Mark. I believe you're advocating for a `final` ServiceException in conjunction with something like
```
class MyAppErrors {
  static ServiceException accessDenied(...) { ...}
  ...
}
```
?

I don't really see a big difference here. Seems like subclassing is the canonical way to customize exceptions, but I don't really too mind either way. (Note that making ServiceException `final` does not mean that `MyAppError#myFooException` couldn't return a `FooException`, of course. I think we actually protect against this by registering exception mapping for ServiceException only in our app server; then throwing FooException is mostly worthless.)

**Comment by markelliot** [comment]
With sub-classing, I’m worried that developers that join a code-base won’t recognize that not all exceptions are created equal. In particular, subclassing will make it less obvious (just by reading code) that there are such a thing as `ServiceException`s or that RandomCassandraException isn’t safe to rethrow for service errors while MySpecializedException is safe to rethrow.

If, instead, we create a factory to produce exceptions (like the one you describe), then when reading the code and seeing thrown exceptions it will be apparent/obvious that something is different.

As an alternative, we can allow sub-classing of exceptions but then need some tooling to, minimally, warn on non-built-in exceptions that don’t extend `ServiceException`. Because we’re in unchecked exception land, it might be hard to make that tooling catch enough of the problem cases.

**Comment by uschi2000** [comment]
OK, sold.

**Pull request closed without merging**
